stations: [18352, 18186]
time_step: 60 # in minutes
organized_dir: "D:/PROJECTS/PyPrecip/examples/outputs/organized"
out_dir: "D:/PROJECTS/PyPrecip/examples/outputs/training_inputs"
short_cols: ["pcp","instm"] # always use pcp for precip, tmp for temperature and rhum for relative humidity. You can define others yourself.
cols: ["precip","insolationtime"] # Select within: ['precip', 'pressure', 'rhum', 'wndsp', 'mxwndsp', 'wnddir_nbr',
                                  #         'radsum', 'rad', 'insolationintensity', 'insolationtime', 'tmp',
                                  #         'minsoiltmp0cm', 'soiltmp5cm',, 'soiltmp10cm', 'soiltmp20cm',
                                  #         'soiltmp50cm', 'soiltmp100cm']

# Precipitation Event Definition Parameters
mit_cold_hours: 1 # cold: Oct–Mar (1h)
mit_warm_hours: 2 # warm: Apr–Sep (2h)
global_event_buffer_hours: 1 # adds buffer hour after each event during determination of global events (for all stations)
event_total_pcp_threshold_4_1hr_event: 1 # event with total precip smaller than this will be ignored (unit should be same as raw input unit. it is mm in this example.)
event_total_pcp_threshold_4_larger_events: 2 # for event greater than 1hr and with total precip smaller than this will be ignored (unit should be same as raw input unit)

## ==== Optional =====
#use_normalized_data: false
#min_max_precip: [0, 50] # if above parameter true (this must be same min max precip used in organizer yaml file)
## options for temperature and relative humidity (consider true if you have them)
#interpolate_tmp_rhum: false # true if you want to interpolate missing temperature and relative humidity
#calculate_diff_tmp_rhum: false # true if you want to calculate difference between now and previous values
#rolling_mean_diff_tmp_rhum: false # true if you want to calculate rolling mean for above diffs
#rolling_mean_diff_tmp_rhum_hour: 10 # if above option true, determine number of hours for rolling mean
## ====================